name: 💡 Feature
description: File an idea/upgradement
title: "[FEATURE] <title>"
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Idea
      description: A description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
